spring:
  application:
    name: functional-router
  data:
    mongodb:
      uri: mongodb://davisito:1234root@localhost:27017/proyecto_2_webflux_functional?authSource=admin
      auto-index-creation: true

jwt:
  secret: 673441e6d97932b815b7058f131cfc10bc12bc8011d5187ab587e5454f426e54
  expiration: 360000
  generator:
    issuer: WEBFLUX-FUNCTIONAL
